Nn/task18
SergeiDemyanenko/PlatformaticaQA_03 pull request #283
Opened 2021-10-31 05:11 UTC by Natalynet

2021-11-02 16:59 UTC, maxsudik requested changes
@Natalynet not sure what to review here.
It fails
```
testAlenaKuts1(GroupMielofonIsMineTest)  Time elapsed: 2.615 sec  <<< FAILURE!
5889
org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
```

2021-11-02 22:07 UTC, Natalynet commented
> @Natalynet not sure what to review here. It fails
> 
> ```
> testAlenaKuts1(GroupMielofonIsMineTest)  Time elapsed: 2.615 sec  <<< FAILURE!
> 5889
> org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
> ```

@maxsudik I fixed them, approve please

2021-11-02 22:15 UTC, maxsudik reviewed
Added a couple of questions...
Some tests are no longer extend base, and one test was removed.

2021-11-02 22:15 UTC, maxsudik commented on src/test/java/WalterBashTest.java
> -
Why is this test was removed?

2021-11-02 22:15 UTC, maxsudik commented on src/test/java/WalterBashTest.java
> -import base.BaseTest;
Why this class doesn't extend base anymore?

2021-11-02 22:15 UTC, maxsudik commented on src/test/java/YuliiaKTest.java
> -import base.BaseTest;
WHy is this test doesn't extend base?

2021-11-02 23:41 UTC, RobinHooD1024 requested changes

2021-11-02 23:41 UTC, RobinHooD1024 commented on src/test/java/RuslanMTest.java
> -        WebElement japaneseLanguage = getDriver().findElement(By.xpath("//div/button[@class='arrow-button forward']/span[text()='" + expectedResult +"']"));
Why did you change another test (not related to your)

2021-11-02 23:41 UTC, RobinHooD1024 commented on src/test/java/GroupBugBustersTest.java
> -    public void testNatalliaMarkhotka_Login() {
method name should start with "test" prefix

2021-11-02 23:41 UTC, RobinHooD1024 commented on src/test/java/BeginnersBottles99Test.java
> -public class BeginnersBottles99Test extends BaseTest {
seems like you didn't pull the the latest main branch

2021-11-02 23:41 UTC, RobinHooD1024 commented on src/test/java/GroupGroupTest.java
> -import base.BaseTest;
same here. Old version of this class.

2021-11-03 00:57 UTC, Natalynet commented on src/test/java/YuliiaKTest.java
> -import base.BaseTest;
This is an old commit, I already merged that. 
And I didn't do anything here, it is probably some conflicting stuff which I fixed and then committed

2021-11-03 00:58 UTC, Natalynet commented on src/test/java/WalterBashTest.java
> -
Same as below, it is an old commit and has been merged a while ago. It is a commit after I resolved conflicts after push

2021-11-03 00:58 UTC, Natalynet commented on src/test/java/WalterBashTest.java
> -import base.BaseTest;
Same as below - old commit - solving of conflicts

2021-11-03 01:01 UTC, Natalynet commented on src/test/java/GroupBugBustersTest.java
> -    public void testNatalliaMarkhotka_Login() {
why?

2021-11-03 01:13 UTC, Natalynet commented on src/test/java/RuslanMTest.java
> -        WebElement japaneseLanguage = getDriver().findElement(By.xpath("//div/button[@class='arrow-button forward']/span[text()='" + expectedResult +"']"));
I didn't change any other tests which are not mine, I think probably it is here because I had an old code, then I pull the new one from the origin main, and then I solved the conflicts.... When I was solving the conflicts I was accepting the origin main changes... So may be that is not new to main. What do you think?

2021-11-03 01:17 UTC, RobinHooD1024 commented on src/test/java/GroupBugBustersTest.java
> -    public void testNatalliaMarkhotka_Login() {
Sergey said that.

2021-11-03 01:19 UTC, RobinHooD1024 commented on src/test/java/RuslanMTest.java
> -        WebElement japaneseLanguage = getDriver().findElement(By.xpath("//div/button[@class='arrow-button forward']/span[text()='" + expectedResult +"']"));
Usually, if you pull the last version of the main branch, it doesn't show in "Files changed". Now it looks like you're trying to change 9 files total, and some of them don't belong to you.

2021-11-03 01:20 UTC, RobinHooD1024 commented on src/test/java/YuliiaKTest.java
> -import base.BaseTest;
Maybe you solved it the wrong way. Try to pull again and carefully look at differences and keep the latest class (if it's not yours).

2021-11-03 01:25 UTC, Natalynet commented on src/test/java/YuliiaKTest.java
> -import base.BaseTest;
Ok, I will try. I have to delete these commits, right?

2021-11-03 01:27 UTC, Natalynet commented on src/test/java/YuliiaKTest.java
> -import base.BaseTest;
Can you please tell me Why I keep seeing all the commits on the 'Comments' Tab (all I did even a month ago), It is confusing, I want to see only which are not merged. Do you have the same?

2021-11-03 03:18 UTC, RobinHooD1024 commented
there are still 5 changed files, I'm pretty sure you didn't mean to change all of them.

2021-11-03 03:27 UTC, RobinHooD1024 requested changes

2021-11-03 03:27 UTC, RobinHooD1024 commented on src/test/java/GroupBugBustersTest.java
>      @Ignore
the refactored test is still ignored

2021-11-03 03:27 UTC, RobinHooD1024 commented on src/test/java/GroupBugBustersTest.java
> -    public void testNatalliaMarkhotka_AddingToWishList() {
Sergey told us about "test" prefix at today's lesson again )

2021-11-03 03:46 UTC, RobinHooD1024 approved these changes
LGFM

2021-11-03 17:06 UTC, maxsudik approved these changes

2021-11-03 17:33 UTC, merged