AP_Entity Default New Record Creating
SergeiDemyanenko/PlatformaticaQA_03 pull request #343
Opened 2021-11-09 00:28 UTC by AnastasiiaPV

2021-11-09 21:39 UTC, OlenaKosenko commented on src/test/java/EntityDefaultTest.java
> +            System.out.println(result.get(i).getText());
No need to print.

2021-11-09 21:42 UTC, OlenaKosenko requested changes

2021-11-09 21:42 UTC, OlenaKosenko commented on src/test/java/EntityDefaultTest.java
> +        for (int i = 0; i < 4; i++) {
4 could be replaced by expectedArray length.

2021-11-09 21:43 UTC, Andrey2694 commented on src/test/java/EntityDefaultTest.java
> +        js.executeScript("arguments[0].scrollIntoView();", plusButton);
we have this method in utils just import it

2021-11-09 22:30 UTC, AnastasiiaPV commented on src/test/java/EntityDefaultTest.java
> +            System.out.println(result.get(i).getText());
All done, thank you!

2021-11-09 22:31 UTC, AnastasiiaPV commented on src/test/java/EntityDefaultTest.java
> +        for (int i = 0; i < 4; i++) {
I have done it. Thank you!

2021-11-09 22:32 UTC, AnastasiiaPV commented on src/test/java/EntityDefaultTest.java
> +        js.executeScript("arguments[0].scrollIntoView();", plusButton);
I have replaced it. Thank you!

2021-11-10 00:56 UTC, OlenaKosenko approved these changes

2021-11-10 05:06 UTC, sviet-ka approved these changes

2021-11-10 05:15 UTC, merged