added verification to set screen size
SergeiDemyanenko/PlatformaticaQA_03 pull request #366
Opened 2021-11-11 09:35 UTC by pavel-sipaty

2021-11-11 10:14 UTC, SergeiDemyanenko requested changes
1. чтобы определить, что мы на сервере у нас есть специальная переменная CI_RUN
2. сейчас в твоем коде делается maximize и устанавливается расширение, нужно написать код так, что работало что-то одно
3. нельзя менять поведение для всех, это очень дурной тон, нужно, что бы после твоих изменений у остальных работало точно так же как и сейчас

2021-11-12 13:58 UTC, SergeiDemyanenko requested changes
1. у нас нет переменной окружения LOCAL_RUN
2. изменения должы быть ткими, чтобы оно не влияло на остальных

2021-11-16 00:08 UTC, SergeiDemyanenko approved these changes

2021-11-16 05:03 UTC, OlenaSMarchenko approved these changes

2021-11-16 08:34 UTC, merged