EntityParentTest, ParentView
SergeiDemyanenko/PlatformaticaQA_03 pull request #416
Opened 2021-11-14 18:55 UTC by MagentaSky125

2021-11-14 20:11 UTC, MagentaSky125 commented on src/test/java/EntityParentTest.java
> +        TestUtils.scrollClick(getDriver(), By.xpath("//div[@id='menu-list-parent']/ul/li[18]/a"));
Yes, you are right. Thx. I've changed

2021-11-14 21:54 UTC, OlenaKosenko commented on src/test/java/EntityParentTest.java
> +        Assert.assertEquals(stringText, s);
AT corresponds to TC. The question is regarding the TC. Why other fields of the Parent form are not filled and verified? Only one field "String" was filled and verified.

2021-11-14 21:56 UTC, OlenaKosenko requested changes

2021-11-14 21:56 UTC, OlenaKosenko commented on src/test/java/EntityParentTest.java
> +    public void testParentViewString () {
redundant space between method name and ()

2021-11-14 22:05 UTC, MagentaSky125 commented on src/test/java/EntityParentTest.java
> +        Assert.assertEquals(stringText, s);
Я за одну проверку проверяю одно поле. Если сразу ввести данные во все поля и тест упадет, то нужно будет разбираться, какое поле дало ошибку. А, если у меня будет несколько тестов, каждый из которых проверяет свое поле, сразу можно будет понять в чем ошибка.

2021-11-14 22:06 UTC, MagentaSky125 commented on src/test/java/EntityParentTest.java
> +    public void testParentViewString () {
ok

2021-11-14 22:55 UTC, ArtsiomAzaranka approved these changes
There are no questions about the autotest.

2021-11-14 23:30 UTC, OlenaKosenko commented on src/test/java/EntityParentTest.java
> +        Assert.assertEquals(stringText, s);
Если тест упадет, то можно посмотреть на каком поле он упал.

2021-11-15 19:27 UTC, MagentaSky125 commented on src/test/java/EntityParentTest.java
> +        Assert.assertEquals(stringText, s);
ок, согласна. Спасибо! Я переделаю

2021-11-17 17:19 UTC, AlexSharon approved these changes

2021-11-17 18:41 UTC, merged