AT_004.01 | Entity > Placeholder > Input (New record with placeholder…
SergeiDemyanenko/PlatformaticaQA_03 pull request #423
Opened 2021-11-14 22:37 UTC by DanaDos

… values)

2021-11-14 23:00 UTC, omalanova approved these changes

2021-11-14 23:17 UTC, OlenaKosenko commented
AT Trello link needs to be in description.

2021-11-14 23:21 UTC, OlenaKosenko commented on src/test/java/EntityPlaceholder2Test.java
> +    private final String expectedString = "String placeholder";
1. Wrong constant name style. Snake case needs to be used. Like EXPECTED_STRING
2. "static" is missing.

2021-11-14 23:27 UTC, OlenaKosenko requested changes
Constants needs to be updated. See comments in the code.

2021-11-15 01:52 UTC, DanaDos commented
AT_004.01.01 | Entity > Placeholder > Input (New record with placeholder values) 
https://trello.com/c/cMxhduBB/402-at0040101-entity-placeholder-input-new-record-with-placeholder-values

2021-11-15 01:54 UTC, DanaDos commented on src/test/java/EntityPlaceholder2Test.java
> +    private final String expectedString = "String placeholder";
Thank you. Mistakes have been fixed.

2021-11-15 02:52 UTC, omalanova approved these changes
Good!

2021-11-15 02:53 UTC, OlenaKosenko submitted a review, later dismissed

2021-11-15 03:00 UTC, alla008 approved these changes
LGFM

2021-11-15 03:06 UTC, merged