AT_006.01.03 | Entity > Reference values > Input (New Record)
SergeiDemyanenko/PlatformaticaQA_03 pull request #432
Opened 2021-11-15 18:30 UTC by OlenaSMarchenko

Fixed assert (Xpath was changed).

2021-11-15 19:05 UTC, OlenaSMarchenko commented
RF_006.01.03 | Entity > Reference values > Input (New Record) #432
https://trello.com/c/LhOk1aZc/426-rf-entityreferencevalues2test-testreferencevaluesinput
https://trello.com/c/2bl5tnDz/337-at0060103-entity-reference-values-input-new-record

@Ignore
https://trello.com/c/XNqgZuK5/427-err-entitygantttest-testentityganttedit

2021-11-15 19:35 UTC, olhakovtun commented
@OlenaSMarchenko 
1. Ссылки на карточки перенесите, пожалуйста, из комментария в описание PR.
2. Название PR должно совпадать с названием карточки RF. Ведь сам тест был добавлен ранее, а сейчас это рефактор.

2021-11-15 20:10 UTC, olhakovtun approved these changes

2021-11-15 20:38 UTC, AlexSharon requested changes
Nice work, but please see my comment

2021-11-15 20:38 UTC, AlexSharon commented on src/test/java/EntityReferenceValues2Test.java
> +        List<WebElement> elements = getDriver().findElements(By.xpath("//tbody/tr/td/a"));
Your test pass even if **List elements** is empty (try pass empty string here "")
I suggest adding check like this:
Assert.assertTrue(elements.size() > 0);

2021-11-15 21:00 UTC, OlenaSMarchenko commented on src/test/java/EntityReferenceValues2Test.java
> +        List<WebElement> elements = getDriver().findElements(By.xpath("//tbody/tr/td/a"));
Thank you, I will check it.

2021-11-15 23:44 UTC, TatianaTOROP approved these changes

2021-11-16 01:56 UTC, AnastasiiaPV approved these changes

2021-11-16 03:53 UTC, AlexSharon approved these changes

2021-11-16 04:58 UTC, merged