AT_019.01.01Entity>Parent>InputNewRecord
SergeiDemyanenko/PlatformaticaQA_03 pull request #470
Opened 2021-11-17 13:46 UTC by Gulya711

TestCreateNewRecord for Parentpage

US:https://trello.com/c/k2xrkLQW/105-us01901-entity-parent-input-new-record
TC:https://trello.com/c/n750IVWT/489-tc0190101-entity-parent-input-new-record
AT:https://trello.com/c/KxHEqiCD/495-at0190101-entity-parent-input-new-record

2021-11-17 19:39 UTC, AlexSharon approved these changes

2021-11-17 20:00 UTC, TorGash24 requested changes

2021-11-17 20:00 UTC, TorGash24 commented on src/test/java/EntityParentInputNewRecordTest.java
> +public class EntityParentInputNewRecordTest extends BaseTest {
Rename class

2021-11-17 20:02 UTC, Gulya711 commented on src/test/java/EntityParentInputNewRecordTest.java
> +public class EntityParentInputNewRecordTest extends BaseTest {
@TorGash24 Why? I followed Irina's rule to be correct.

2021-11-18 02:45 UTC, TatianaTOROP approved these changes

2021-11-18 02:45 UTC, TatianaTOROP commented on src/test/java/EntityParentInputNewRecordTest.java
> +public class EntityParentInputNewRecordTest extends BaseTest {
It is fine, but could be better EntityParentTest

2021-11-18 02:50 UTC, Gulya711 commented on src/test/java/EntityParentInputNewRecordTest.java
> +public class EntityParentInputNewRecordTest extends BaseTest {
> It is fine, but could be better EntityParentTest

I got it, for a next time I will know it, thank you.

2021-11-18 09:42 UTC, olhakovtun commented on src/test/java/EntityParentInputNewRecordTest.java
> +public class EntityParentInputNewRecordTest extends BaseTest {
> Rename class

@TorGash24 Подскажите, пожалуйста, по какой причине класс нужно переназвать?

2021-11-18 09:43 UTC, olhakovtun commented on src/test/java/EntityParentInputNewRecordTest.java
> +public class EntityParentInputNewRecordTest extends BaseTest {
> It is fine, but could be better EntityParentTest

@TatianaTOROP Класс EntityParentTest уже существует

2021-11-18 14:49 UTC, olhakovtun commented on src/test/java/EntityParentInputNewRecordTest.java
> +public class EntityParentInputNewRecordTest extends BaseTest {
> > Rename class
> > InputNewRecord -это относится к тесту, а не к классу.
@TorGash24 
Возможно это не самое удачное название для класса, но на данном этапе это допустимо, тем более в классе находится только одноимённый тест. Из требований Сергея - вначале Entity в конце Test. Если других замечаний нет, снимите, пожалуйста, блок.

2021-11-18 15:56 UTC, TorGash24 approved these changes

2021-11-19 04:04 UTC, Gulya711 commented on src/test/java/EntityParentInputNewRecordTest.java
> +        final String Int = "1";
@TorGash24 corrected!

2021-11-19 04:04 UTC, Gulya711 commented on src/test/java/EntityParentInputNewRecordTest.java
> +        getDriver().findElement(By.id("string")).sendKeys("Gulya");
@TorGash24 Removed, thanks

2021-11-19 19:17 UTC, merged