TC_011.01 | Entity > Board > Create new record (with new values)
SergeiDemyanenko/PlatformaticaQA_03 pull request #582
Opened 2021-11-23 04:53 UTC by leokons

https://trello.com/c/vaRwVYwA/485-tc01101-entity-board-create-new-record-with-new-values

2021-11-23 23:27 UTC, TatianaTOROP approved these changes

2021-11-24 01:56 UTC, MariaMoroz requested changes
А на каком основании поставлен игнор на тест из другого класса? Где карточка на ошибку и не видно, чтобы PR падал на этом тесте .

2021-11-24 01:57 UTC, MariaMoroz commented
Название пиара надо заменить на AT_011.01 | Entity > Board > Create new record (with new values) и карточку сюда надо присоединить на automation вместо ТС

2021-11-24 04:44 UTC, MariaMoroz approved these changes

2021-11-24 16:39 UTC, merged