RF_006.01.07 | Entity > Reference values > Input (New record) - Save as draft
SergeiDemyanenko/PlatformaticaQA_03 pull request #736
Opened 2021-12-04 06:16 UTC by BloodyAshes

https://trello.com/c/OfFsuhNh/847-at0060107-entity-reference-values-input-new-record-save-as-draft

2021-12-04 08:02 UTC, pavel-sipaty commented on src/test/java/EntityReferenceValues6Test.java
> +    final String[] VALUES = new  String[]{"LabelTest", "Filter1Test", "Filter2Test"};
Fields of classes should be in the beginning of class, before all methods.

2021-12-04 08:03 UTC, pavel-sipaty requested changes
I've commented the line 32. Please make changes.

2021-12-04 16:40 UTC, AnastasiiaPV approved these changes

2021-12-05 08:18 UTC, kololesya approved these changes

2021-12-05 10:12 UTC, pavel-sipaty requested changes

2021-12-05 10:12 UTC, pavel-sipaty commented on src/test/java/EntityReferenceValues6Test.java
> +    final String[] VALUES = new  String[]{"LabelTest", "Filter1Test", "Filter2Test"};
Didn't see any changes from you side or your comments according to my note.

2021-12-06 07:16 UTC, pavel-sipaty approved these changes

2021-12-06 13:32 UTC, merged