AT_018.01.17 | Entity > Arithmetic Function > Test of * - + /** > New record
SergeiDemyanenko/PlatformaticaQA_03 pull request #751
Opened 2021-12-05 06:47 UTC by annapav7

At 018.01.17 entity arithmetic function test new record:

US: https://trello.com/c/TMkymk8j/522-us01801-entity-arithmetic-function-test-of-new-record;
TC: https://trello.com/c/eqS5QSK7/579-tc0180117-entity-arithmetic-function-test-of-new-record;
AT: https://trello.com/c/S56P5vPM/580-at0180117-entity-arithmetic-function-test-of-new-record.

2021-12-07 21:18 UTC, OlenaSMarchenko approved these changes

2021-12-09 01:59 UTC, ke-de-ve requested changes

2021-12-09 01:59 UTC, ke-de-ve commented on src/test/java/EntityArithmeticFunction_018_01_17Test.java
> +        scrollClick(getDriver(), By.xpath("//div[@id = 'menu-list-parent']//p[text() = ' Arithmetic Function ']"));
is there anything in between div and p?

2021-12-09 01:59 UTC, ke-de-ve commented on src/test/java/EntityArithmeticFunction_018_01_17Test.java
> +        List<WebElement> elements = getDriver().findElements(By.xpath("//tbody/tr/td/a"));
need to search for elements inside of the rows
rows.findElements(By....

2021-12-13 04:23 UTC, closed without merging