AT_024.04.04 | Entity > Platform functions > Delete record
SergeiDemyanenko/PlatformaticaQA_03 pull request #823
Opened 2021-12-09 18:53 UTC by AnastasiiaPV

AT_024.04.04 | Entity > Platform functions > Delete record
https://trello.com/c/zcSlz5Jf/1030-at0240404-entity-platform-functions-delete-record

2021-12-09 19:21 UTC, kololesya approved these changes

2021-12-09 20:16 UTC, Stan575 requested changes

2021-12-09 20:27 UTC, Stan575 commented on src/test/java/EntityPlatformFunctions1Test.java
> +        waitToBeClickableClick(By.xpath(SHOWING_1_TO_2_OF_2_ROWS));
see line 226, line 233 does essentially the same

2021-12-09 20:59 UTC, AnastasiiaPV commented on src/test/java/EntityPlatformFunctions1Test.java
> +        waitToBeClickableClick(By.xpath(SHOWING_1_TO_2_OF_2_ROWS));
I came up with this Idea just to have additional time to wait till three lines will be changed by two lines.

2021-12-09 21:01 UTC, AnastasiiaPV commented on src/test/java/EntityPlatformFunctions1Test.java
> +        waitToBeClickableClick(By.xpath(SHOWING_1_TO_2_OF_2_ROWS));
And this seems to me like good additional asserting.

2021-12-10 01:53 UTC, Stan575 commented on src/test/java/EntityPlatformFunctions1Test.java
> +        waitToBeClickableClick(By.xpath(SHOWING_1_TO_2_OF_2_ROWS));
got it, when you exploit some kinda workaround waiter it's good to make it easy to understand by just looking at the code
in this case it looks very suspicious for another person who doesn't know your intention

2021-12-10 01:54 UTC, Stan575 approved these changes
approved, think how to make that waiting part looking better

2021-12-10 02:15 UTC, AnastasiiaPV commented on src/test/java/EntityPlatformFunctions1Test.java
> +        waitToBeClickableClick(By.xpath(SHOWING_1_TO_2_OF_2_ROWS));
Thank you, Stan. Will try to do my best.

2021-12-10 02:17 UTC, merged