RF | Platform Functions > refactoring of tests (POM with generics)
SergeiDemyanenko/PlatformaticaQA_03 pull request #992
Opened 2021-12-27 13:59 UTC by AlexSharon

Refactoring https://trello.com/c/5Xyl2q3z

2021-12-27 15:22 UTC, pavel-sipaty commented on src/test/java/model/platformFunctions/PlatformFunctionsBinPage.java
> +    public PlatformFunctions2Page assertRecycleBinIsEmpty() {
Asserts should not be in model classes.

2021-12-27 15:23 UTC, pavel-sipaty requested changes
Sergey said that Asserts should not be in model classes.

2021-12-27 15:34 UTC, AlexSharon commented on src/test/java/model/platformFunctions/PlatformFunctionsBinPage.java
> +    public PlatformFunctions2Page assertRecycleBinIsEmpty() {
Please refer to the latest lesson of Sergei, time code 1.35:10

2021-12-27 15:34 UTC, AlexSharon commented
> Sergey said that Asserts should not be in model classes.

Then he said different thing last week.

2021-12-27 18:48 UTC, IrinaRiz approved these changes

2021-12-28 04:19 UTC, VasiliyTsoy approved these changes

2021-12-28 06:50 UTC, pavel-sipaty approved these changes

2021-12-28 07:21 UTC, merged