RF | BaseViewPage > BaseViewPageAdditional
SergeiDemyanenko/PlatformaticaQA_03 pull request #999
Opened 2021-12-28 16:14 UTC by kololesya

https://trello.com/c/ljGJFa17/1260-rf-baseviewpage-baseviewpageadditional

2021-12-28 16:30 UTC, SergeiDemyanenko requested changes

2021-12-28 16:30 UTC, SergeiDemyanenko commented on src/test/java/model/base/BaseViewPageAdditional.java
> +package model.base;
Название класса должно заканчиваться на Page и должно как-то соотносится с тем, что делает этот класс. Например: BaseViewAsListPage

2021-12-28 16:30 UTC, SergeiDemyanenko commented on src/test/java/model/base/BaseViewPage.java
> +//    private List<WebElement> actualValues;
Комментраии в коде не допустимы.

2021-12-28 16:30 UTC, SergeiDemyanenko commented on src/test/java/model/base/BaseViewPage.java
> +//    }
Комментраии в коде не допустимы.

2021-12-28 16:30 UTC, SergeiDemyanenko commented on src/test/java/model/base/BasePage.java
>  import java.util.List;
Изменени в этом классе не имеют смыслы, если их отменить, то ничего не изменится, а будет только лучше из-за дополнительных проверок и более понятного названия обобщенного типа (ViewPageType vs T).

2021-12-28 16:30 UTC, SergeiDemyanenko commented on src/test/java/model/arithmeticInline/ArithmeticInlineViewPage.java
> +//    }
Комментраии в коде не допустимы.

2021-12-28 16:30 UTC, SergeiDemyanenko commented on src/test/java/model/base/BaseViewPageAdditional.java
> +public abstract class BaseViewPageAdditional <MainPageType extends BasePage<MainPageType, ?, ?>> extends BaseViewPage{
Ты теряешь тут связь с MainPageType т.к. не передаешь этот тип дальше. Скорее всего IDE подсветила тебе слово **BaseViewPage** в этой строке, но ты не обратил на это внимание.

public abstract class BaseViewPageAdditional<MainPageType extends BasePage<MainPageType, ?, ?>> extends BaseViewPage<MainPageType> {

2021-12-28 16:30 UTC, SergeiDemyanenko commented on src/test/java/model/base/BaseViewPageAdditional.java
> +    protected abstract MainPageType createMainPage();
В этой строчке нет смыслы, перекрвать абстрактный метод абстрактным методом е тнеобходимости, ничего не меняется, а только усложняется понимание структуры. Просто удали это и все.

2021-12-28 16:30 UTC, SergeiDemyanenko commented on src/test/java/model/arithmeticInline/ArithmeticInlineViewPage.java
> +public class ArithmeticInlineViewPage extends BaseViewPageAdditional {
Тут придется вернуть предыдущую строку после испралений в классе BaseViewPageAdditional

2021-12-29 08:41 UTC, kololesya commented
запуталась в комиттах, сделаю новый pr

2021-12-29 08:41 UTC, closed without merging